### ISSUE TITLE
Make Linear Algebra Calculator

### ISSUE THREAD

**Issue by dummyindex** [UCSB-CS56-Projects/cs56-android-conversion-showdown#14]
Make Linear Algebra Calculator.
1. Not use a library:
matrix, vector operations 100pts each
Gaussian Elimination, Inverse Matrix, Orthogonalize, etc: each algorithm worth 50-100pts 
2. Wisely Use Library instead of implementing: 250pts

Should include a basic user interface.

**Comment by ntpincus** [comment]
M16 OK

**Comment by vivekpatel42** [comment]
F16 CLOSED: Task goes out of the scope of the app's functionality.
