### ISSUE TITLE
Better User Interface

### ISSUE THREAD

**Issue by dummyindex** [UCSB-CS56-Projects/cs56-android-conversion-showdown#15]
change interfaces to android guidlines (potentially add fragments to activities)
100pts

**Comment by vivekpatel42** [comment]
Update user interface to stay consistent in aesthetic appeal when rotating to landscape mode.

**Comment by vivekpatel42** [comment]
F16 OK (150 pts)

**Comment by seemantasaha** [comment]
Hopefully will be covered by #19
