### ISSUE TITLE
Add More Tests

### ISSUE THREAD

**Issue by dummyindex** [UCSB-CS56-Projects/cs56-android-conversion-showdown#20]
There're many functions without any tests.
Also there's no integration test. Overall now this code is not reliable. It is just working without obvious bugs.

50 - 200 pts, depends on how many tests were created.

**Comment by ntpincus** [comment]
M16-OK

**Comment by vivekpatel42** [comment]
F16 OK (100 pts)

**Comment by YunSuk** [comment]
baseCalculatorTest and other UI components could use more tests.

F17 OK (100 points)

**Comment by seemantasaha** [comment]
W18 OK. 100 points.

**Comment by seemantasaha** [comment]
Resolved.
