### ISSUE TITLE
Better documentation in code

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-android-conversion-showdown#26]
Add better documentation (more descriptive Javadoc comments) to the code header and long methods with a lot of logical branching.

**Comment by vivekpatel42** [comment]
F16 OK (75 pts)

**Comment by vivekpatel42** [comment]
F16 OK (75 pts)

**Comment by seemantasaha** [comment]
Opened a new issue #63
