### ISSUE TITLE
Add javadocs

### ISSUE THREAD

**Issue by YunSuk** [UCSB-CS56-Projects/cs56-android-conversion-showdown#45]
This project is missing javadocs for most functions and classes.
Please add javadocs.

150 points

**Comment by Tianyi6679** [comment]
Working on it

**Comment by YunSuk** [comment]
Implemented javadoc for many of the classes and methods, but there are still functions that are missing javadocs. Also, many javadocs are missing param descriptions

**Comment by YunSuk** [comment]
Will open separate issue for above problem
