### ISSUE TITLE
This number is too large error

### ISSUE THREAD

**Issue by YunSuk** [UCSB-CS56-Projects/cs56-android-conversion-showdown#46]
During binary conversion quiz, you get number is too large warning when you enter more 8 digits.
For some of the quizzes, the answer is more than 8 digits.
Make sure you allow more digits (either infinite or limit to max number digits that the tests expects for an answer)

75 points

**Comment by Tianyi6679** [comment]
working on it

**Comment by Tianyi6679** [comment]
Problem fixed. Extra work: adjust textview accordingly so that text will not overlap with other buttons. Would you please add 25pts for this extra fix?

**Comment by YunSuk** [comment]
Ok. 100 points
