### ISSUE TITLE
Calculator's first and second input base does not work properly

### ISSUE THREAD

**Issue by YunSuk** [UCSB-CS56-Projects/cs56-android-conversion-showdown#47]
In calculator activity, when you have different bases for first and second input, it produces wrong output.

Make sure it produces correct output when the bases are different.

Also, see testCalcHex(). <- which fails for 2 reasons (this issue (#47) and issue #40)

75 points

**Comment by seemantasaha** [comment]
W18 OK. 50 points.

**Comment by seemantasaha** [comment]
Resolved.
