### ISSUE TITLE
App crashes when it starts in landscape view

### ISSUE THREAD

**Issue by YunSuk** [UCSB-CS56-Projects/cs56-android-conversion-showdown#49]
App crashes when it starts in landscape view. It also crashes when rotating to landscape on the welcome screen.

150 points

**Comment by chuchengLin** [comment]
Can I get 75 points for fixing the second part of this issue?

**Comment by YunSuk** [comment]
Fix the welcome page, but not the start page. App still crashes when it is launched in landscape mode.

**Comment by seemantasaha** [comment]
Issue #58 will cover this issue.
