### ISSUE TITLE
Correct back button behavior

### ISSUE THREAD

**Issue by YunSuk** [UCSB-CS56-Projects/cs56-android-conversion-showdown#50]
Back button from quiz score screen should take you to main screen.

 100 points

**Comment by chuchengLin** [comment]
working on this

**Comment by chuchengLin** [comment]
Fix problem where pressing back button on the main screen going into previously took quiz screen
100 points

**Comment by chuchengLin** [comment]
Fix two more back buttons: When click calculator in ScoreReport page and leads to the baseCalculator page, clicking back button will lead to ScoreReport Page. The same when click Text new quiz in ScoreReport page. 
100 points

**Comment by YunSuk** [comment]
Ok 200 points in total

**Comment by YunSuk** [comment]
When in ScoreReport, press back button goes to main page. When you press back button again, it does not work properly

100 points

**Comment by chuchengLin** [comment]
Hi Yun, can you remind me how many points did we earn for the whole legacy project? I want to have an insight how many extra credit do we have. Thank you.

Sincerely
Chucheng Lin

Sent using OWA for iPhone
________________________________

**Comment by seemantasaha** [comment]
I have opened new issue #62 to remove all confusion.
