### ISSUE TITLE
Make a new layout for welcome page to make it suitable to landscape view

### ISSUE THREAD

**Issue by chuchengLin** [UCSB-CS56-Projects/cs56-android-conversion-showdown#58]
Currently, in the welcome page, the images are scaled to be smaller while trying to fix issue #49 in order to prevent from overlapping in landscape view.

However, this made the welcome screen awkward since there are extra empty spaces that are not getting used.

Make a new layout for welcome page so that the image fits well to the landscape view and still do not have overlapping issue.

**Comment by YunSuk** [comment]
F17 OK. 150 points

**Comment by seemantasaha** [comment]
W18 OK. 150 points.

**Comment by seemantasaha** [comment]
Resolved.
