### ISSUE TITLE
Fix TextView disappearing bug while taking the DEC-BIN quiz

### ISSUE THREAD

**Issue by chuchengLin** [UCSB-CS56-Projects/cs56-android-conversion-showdown#60]
Fix the bug in DEC to BIN quiz: switching to landscape and switching back causes answer TextView to disappear.

**Comment by YunSuk** [comment]
F17 OK. 150 points

**Comment by seemantasaha** [comment]
W18 OK. 150 points.

**Comment by seemantasaha** [comment]
Not reproducible.
