### ISSUE TITLE
Detailed Feedback

### ISSUE THREAD

**Issue by ashedden** [UCSB-CS56-Projects/cs56-android-conversion-showdown#7]
Issue: Create an Activity to display detailed quiz feedback (wrong answers) via a button in ScoreReportActivity. Have ScoreReport Activity only display percentage of each question type scored correctly.
150 points

**Comment by ntpincus** [comment]
M16 OK

**Comment by vivekpatel42** [comment]
Still need to correctly display correct score percentage on ScoreReportActivity at end of the quiz.

**Comment by vivekpatel42** [comment]
F16 OK (100 pts)

**Comment by YunSuk** [comment]
Resolved
